driver:
  name: vagrant
  forward_agent: yes
  customize:
    cpus: 4
    memory: 2048
  synced_folders:
    - ['.', '/home/vagrant/apitools-monitor']

provisioner:
  name: chef_zero
  require_chef_omnibus: 11.16.4

platforms:
  - name: ubuntu-14.04
    run_list: apt::default
  - name: ubuntu-12.04
    run_list: apt::default
  # - name: debian-8.0.0
  #  run_list: apt::default
  - name: debian-7.2.0
    run_list: apt::default

suites:
  - name: apitools
    run_list:
    - omnibus::default
    - unzip
    - omnibus-sbin-path
    - nodejs::npm
    attributes:
      omnibus:
        build_user:          vagrant
        build_user_group:    vagrant
        build_user_password: vagrant
        install_dir:         /opt/apitools-monitor
